### ISSUE TITLE
Always add timeout to http clients

### ISSUE THREAD

**Issue by gaborszakacs** [bitrise-steplib/bitrise-step-artifact-pull#13]
As there's none set in the default client.

https://github.com/bitrise-steplib/bitrise-step-artifact-pull/blob/c23735226462630549fe37cd44ad0f22659992ce/downloader/file_downloader.go#L20

**Comment by lpusok** [comment]
Would reccomend go-utils / go-steputils package as used here: https://github.com/bitrise-io/go-xcode/blob/99a08cd4c73d98db0dedac5e3bd1a64c2f45203a/autocodesign/certdownloader/certdownloader.go#L58

Also (go-utils) retry.NewHTTPClient().StandardClient() for a HTTP client that does retries (this is a wrapper for go-retryablehttp package)

**Comment by gaborszakacs** [comment]
Thanks, nice! I should've supposed you have tools for these :D
