### ISSUE TITLE
Consider changing this line to reflect that this step can only be done by Bitrise internal engineers

### ISSUE THREAD

**Issue by miklosboros** [bitrise-steplib/bitrise-step-artifact-pull#22]
The described process can only be done by someone from Bitrise. Consider changing this sentence to reflect this, also fix the typo in `LasPass`

https://github.com/bitrise-steplib/bitrise-step-artifact-pull/blob/73f260ac8e45f47213ac6b2c01663689eb3a08f9/README.md?plain=1#L72

**Comment by imrekel** [comment]
https://github.com/bitrise-steplib/bitrise-step-artifact-pull/pull/30
