### ISSUE TITLE
Having 2 `ListBuildArtifacts` methods with slightly different signature can be a bit confusing, consider making them differ more more 

### ISSUE THREAD

**Issue by gaborszakacs** [bitrise-steplib/bitrise-step-artifact-pull#34]
They are on different structs, one is on the APIClient and one is on the ArtifactLister, but it can get quite confusing for the reader.

E.g. a `ListBuildArtifacts` test is starting with mocking the `ListBuildArtifacts` method (not the same, but it took me some time to understand).

Slightly related, not sure if the API Client methods need to be public, seems like we only use the ListBuildArtifacts in the step. Even the API Client init could be an implementation detail of the lister (don't need to happen in `step.go`, unless we expect we will use the client directly here later on.

**Comment by imrekel** [comment]
* I altered the lister method name a bit (`ListBuildArtifactDetails`) - let me know if you have a better idea :) I don't want to change the name of the client's method because that matches the name of the endpoint definition in
* Moved methods/interfaces to private
* I wonder if using an internal constructor with a lowercase name (that allows mocking) is an acceptable pattern

**Comment by gaborszakacs** [comment]
> I altered the lister method name a bit (ListBuildArtifactDetails) - let me know if you have a better idea :) I don't want to change the name of the client's method because that matches the name of the endpoint definition in

Anything that's not the very same name is an improvement, IMO, maybe we can try `GetBuildArtifactsWithDownloadURL` to indicate that what makes this special is that it returns the download URL too (for me `Path` often means a relative path, i.e. without the domain, that's why I'd prefer URL)

> I wonder if using an internal constructor with a lowercase name (that allows mocking) is an acceptable pattern

Yeah, you're right, I guess we should leave it to the caller then so one can inject a different API client (e.g. a mock one).
