### ISSUE TITLE
Consider passing in a writer instead of returning with a slice of bytes

### ISSUE THREAD

**Issue by gaborszakacs** [bitrise-steplib/bitrise-step-artifact-pull#49]
I'm not sure how the shared file/downloader utils supposed to be used but returning with a slice of bytes is generally not considered idiomatic, one way we usually deal with this is e.g. passing in a writer instead and let the function write into it.

Maybe we can ask for a CoreSteps member for advice here(?)

https://github.com/bitrise-steplib/bitrise-step-artifact-pull/blob/a0691e3046e0fd3933bab3a7c6067aca2666ac11/downloader/file_downloader.go#L23

**Comment by sylank** [comment]
use the following function: https://github.com/bitrise-steplib/bitrise-step-artifact-pull/blob/a0691e3046e0fd3933bab3a7c6067aca2666ac11/vendor/github.com/bitrise-io/go-utils/filedownloader/filedownloader.go#L58
